---
# handlers file for my_mysql

- name: Generate password random
  set_fact:
       mysql_root_password: "{{ lookup('password', '/dev/null length=15 chars=ascii_letters') }}"
       mysql_tsv_password: "{{ lookup('password', '/dev/null length=15 chars=ascii_letters') }}"
#- debug:
#       msg: "{{ mysql_root_password }}"
#       msg: "{{ mysql_tsv_password }}"

- name: Create my.cnf with root password credentials
  become: yes
  no_log: yes
  template:
       src:  my.cnf.j2
       dest: /root/.my.cnf
       owner: root
       group: root
       mode: 0600
  loop:
       - password: "{{ mysql_root_password }}"

- name: Create user root
  become: true
  no_log: true
  mysql_user:
       name: "{{ mysql_root_user }}"
       host: "{{ item }}"
       password: "{{ mysql_root_password }}"
       login_user: "{{ mysql_root_user }}"
       login_password: "{{ mysql_root_password }}"
       check_implicit_admin: yes
       state: present
       update_password: always
  loop:
       - 127.0.0.1
       - localhost
     
     
- name: Create user tsv
  become: true
  no_log: true
  mysql_user:
       name: "{{ mysql_tsv_user }}"
       host: "{{ item }}"
       password: "{{ mysql_tsv_password }}"
       login_user: "{{ mysql_root_user }}"
       login_password: "{{ mysql_root_password }}"
       check_implicit_admin: yes
       priv: "*.*:ALL"
       state: present
       update_password: always
  loop:
       - 127.0.0.1
       - localhost
       - "{{ ansible_host }}"



- name: Create role
  become: true
  community.mysql.mysql_role:
       name: developers
       state: present
       login_user: "{{ mysql_root_user }}"
       login_password: "{{ mysql_root_password }}"
       check_implicit_admin: yes
       priv: "*.*:ALL"
       members:
       - 'root@{{item}}'
       - 'tsv@{{item}}'
       set_default_role_all: no
  loop:
       - 127.0.0.1
       - localhost



- name: Create the MySQL database
  community.mysql.mysql_db:
    check_implicit_admin: no
    login_user: "{{ mysql_tsv_user }}"
    login_password: "{{ mysql_tsv_password }}" 
    name: tsv_bd
    state: present


